version: "3.3"
services:
  dufs:
    user: "1001"
    container_name: "dufs-dc"
    restart: "always"
    image: sigoden/dufs:v0.29.0
    ports:
      - 5000:5000
    volumes:
      - /mnt/disk:/data
    command: "-A /data"
